modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/UpperMoon0/OpenUI-MC/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.openui_mc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openui_mc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"
