modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/UpperMoon0/OpenUI-MC/issues"

[[mods]]
modId = "openui_mc"
version = "${version}"
displayName = "OpenUI MC"
authors = "NsTut"
description = '''
A reusable, composable UI framework for Minecraft mods.
'''

[[dependencies.openui_mc]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openui_mc]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

