plugins { id 'com.gradleup.shadow' }
loom { forge { } }
architectury { platformSetupLoomIde(); forge() }

configurations {
    common { canBeResolved = true; canBeConsumed = false }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
    shadowBundle { canBeResolved = true; canBeConsumed = false }
}

dependencies {
    api project(':common-1.20.1')
    forge "net.minecraftforge:forge:${rootProject.forge_version_1_20_1}"
    common(project(path: ':common-1.20.1', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common-1.20.1', configuration: 'transformProductionForge')
}

processResources {
    def metadata = [
        version: project.version,
        mod_id: rootProject.mod_id,
        mod_name: rootProject.mod_name,
        mod_description: rootProject.mod_description,
        mod_authors: rootProject.mod_authors,
        mod_license: rootProject.mod_license
    ]
    inputs.properties metadata
    filesMatching('META-INF/mods.toml') { expand metadata }
}
shadowJar { configurations = [project.configurations.shadowBundle]; archiveClassifier = 'dev-shadow' }
remapJar { inputFile.set shadowJar.archiveFile }
